### ISSUE TITLE
The form should be displayed either in a pop-up or a new page when clicked on Register Here button.

### ISSUE THREAD

**Issue by wigNepal** [wigNepal/wigNepal-website#2]
**Description:**
We are creating an online registration form for members in Women in Geospatial Nepal, the submissions will be stored in our database. 
The fields in the form only include Name, Email and Contact number as of now.

Issues:

The registration form appears on the bottom of the page and is hidden.

Expectation:
The form should appear either on a pop-up or a new page when clicked on Register Here button.
![Uploading image.png…]()

**Comment by susmina94** [comment]
https://go.screenpal.com/watch/cZiIXdVPcQP
