### ISSUE TITLE
Add social media links on the header and footer of the website

### ISSUE THREAD

**Issue by wigNepal** [wigNepal/wigNepal-website#3]
Facebook: https://www.facebook.com/womeningeospatial
Linkedin: https://www.linkedin.com/in/women-in-geospatial-nepal-2774322b9/

**Comment by susmina94** [comment]
![image](https://github.com/user-attachments/assets/75c9e204-590d-4994-8e9c-921cdbeced00)

**Comment by susmina94** [comment]
https://go.screenpal.com/watch/cZiIXdVPcQP
